<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBj4usic\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBj4usic/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBj4usic.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBj4usic\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBj4usic\appProdProjectContainer([
    'container.build_hash' => 'Bj4usic',
    'container.build_id' => '6eb5f089',
    'container.build_time' => 1701717972,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBj4usic');
