<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBunfdhs\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBunfdhs/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBunfdhs.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBunfdhs\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBunfdhs\appProdProjectContainer([
    'container.build_hash' => 'Bunfdhs',
    'container.build_id' => 'd8bb0704',
    'container.build_time' => 1700322621,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBunfdhs');
