<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxon0xq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxon0xq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSxon0xq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSxon0xq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSxon0xq\appProdProjectContainer([
    'container.build_hash' => 'Sxon0xq',
    'container.build_id' => '2745bd12',
    'container.build_time' => 1700209756,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxon0xq');
